# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "httparty", "~> 0.19.0"
gem "aws-sdk-route53", "~> 1.55"
